/**
 * striverSeedReady.js — AUTO GENERATED
 * Generated by fetchStriverPlaylist.js
 * Contains REAL video IDs from playlist: PLgUwDviBIf0oF6QL8m22w1hIDC1vJ_BHz
 * Total videos: 316
 *
 * USAGE: Copy striverA2Z object into your seedCourses.js
 */

import mongoose from "mongoose";
import dotenv from "dotenv";
import path from "path";
import { fileURLToPath } from "url";
import Course from "../models/course.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
dotenv.config({ path: path.join(__dirname, "../.env") });

const yt  = (id) => `https://www.youtube.com/embed/${id}`;
let order = 1;
const lec = (id, title, duration, isFree = false) => ({
  lectureId:      `lec_str_${order}`,
  lectureTitle:   title,
  lectureDuration: duration,
  lectureUrl:     yt(id),
  isPreviewFree:  isFree,
  lectureOrder:   order++,
});

const striverA2Z = {
  courseTitle: "Striver's A2Z DSA Course — Complete by takeUforward",
  courseDescription: `<p>The most in-depth, structured, and free DSA course by 
    <strong>Raj Vikramaditya (Striver)</strong> — Ex Google, Amazon engineer 
    and founder of takeUforward. Covers 454 problems across 18 steps.</p>
    <p><strong>Topics:</strong> Arrays, Strings, Linked Lists, Stacks, Queues, 
    Binary Search, Recursion, Bit Manipulation, Trees, Graphs, Heaps, Greedy, 
    Tries, Dynamic Programming — all patterns from basics to FAANG level.</p>`,
  courseThumbnail: "https://img.youtube.com/vi/EAR7De6Goz4/maxresdefault.jpg",
  coursePrice:     0,
  discount:        0,
  isPublished:     true,
  educator:        "admin",
  enrolledStudents: [],
  courseRatings:   [],
  courseContent: [
    {
      chapterId: "ch_str_01",
      chapterOrder: 1,
      chapterTitle: "Step 1 – Learn the Basics (C++ / Java + Math + Hashing)",
      chapterContent: [
        lec("0bHoB32fuj0", "Don\\'t watch my A2Z DSA Course", 20, true),
        lec("h3uDCJ5mvgw", "How to setup VS code for DSA and CP | Input / Output split format", 20, true),
        lec("EAR7De6Goz4", "C++ Basics in One Shot - Strivers A2Z DSA Course - L1", 20),
        lec("FPu9Uld7W-E", "Time and Space Complexity - Strivers A2Z DSA Course", 20),
        lec("tNm_NNSB3_w", "Solve any Pattern Question - Trick Explained | 22 Patterns in 1 Shot | Strivers A2Z DSA Course", 20),
        lec("RRVYpIET_RU", "Complete C++ STL in 1 Video | Time Complexity and Notes", 20),
        lec("1xNbjMdbjug", "Basic Maths for DSA | Euclidean Algorithm | Strivers A2Z DSA Course", 20),
        lec("yVdKa8dnKiE", "Re 1. Introduction to Recursion | Recursion Tree | Stack Space | Strivers A2Z DSA Course", 20),
        lec("un6PLygfXrA", "Re 2. Problems on Recursion | Strivers A2Z DSA Course", 20),
        lec("69ZCDFy-OUo", "Re 3. Parameterised and Functional Recursion | Strivers A2Z DSA Course", 20),
        lec("twuC1F6gLI8", "Re 4. Problems on Functional Recursion | Strivers A2Z DSA Course", 20),
        lec("kvRjNm4rVBE", "Re 5. Multiple Recursion Calls | Problems | Strivers A2Z DSA Course", 20),
        lec("KEs5UyBJ39g", "Hashing | Maps | Time Complexity | Collisions | Division Rule of Hashing | Strivers A2Z DSA Course", 20),
        lec("HGk_ypEuS24", "Sorting - Part 1 | Selection Sort, Bubble Sort, Insertion Sort | Strivers A2Z DSA Course", 20),
        lec("ogjf7ORKfd8", "Merge Sort | Algorithm | Pseudocode | Dry Run | Code | Strivers A2Z DSA Course", 20),
        lec("WIrA4YexLRQ", "Quick Sort For Beginners | Strivers A2Z DSA Course", 20),
        lec("37E9ckMDdTk", "Find Second Largest Element in Array | Remove duplicates from Sorted Array | Arrays Intro Video", 20),
        lec("wvcQg43_V8U", "Rotate Array by K places | Union, Intersection of Sorted Arrays | Move Zeros to End | Arrays Part-2", 20),
        lec("bYWLJb3vCWY", "Find element that appears once | Find missing number | Max Consecutive number of 1\\'s | Arrays Part-3", 20),
        lec("frf7qxiN2qU", "Longest Subarray with sum K | Brute - Better - Optimal | Generate Subarrays", 20),
        lec("UXDSeD9mN-k", "2 Sum Problem | 2 types of the same problem for Interviews | Brute-Better-Optimal", 20),
        lec("tp8JIuCXBaU", "Sort an array of 0\\'s 1\\'s & 2\\'s | Intuition of Algo🔥 | C++ Java Python | Brute-Better-Optimal", 20),
        lec("nP_ns3uSh80", "Majority Element I | Brute-Better-Optimal | Moore\\'s Voting Algorithm | Intuition 🔥|Brute to Optimal", 20),
        lec("AHZpyENo7k4", "Kadane\\'s Algorithm | Maximum Subarray Sum | Finding and Printing", 20),
        lec("excAOvwF_Wk", "DP 35. Best Time to Buy and Sell Stock | DP on Stocks 🔥", 20),
        lec("h4aBagy4Uok", "Rearrange Array Elements by Sign | 2 Varieties of same Problem", 20),
        lec("JDOXKqF60RQ", "Next Permutation - Intuition in Detail 🔥 | Brute to Optimal", 20),
        lec("cHrH9CQ8pmY", "Leaders in an Array | Brute - Optimal | Strivers A2Z DSA Course", 20),
        lec("oO5uLE7EUlM", "Longest Consecutive Sequence | Google Interview Question | Brute Better Optimal", 20),
        lec("N0MgLvceX7M", "Set Matrix Zeroes | O(1) Space Approach | Brute - Better - Optimal", 20),
        lec("Z0R2u6gd3GU", "Rotate Matrix/Image by 90 Degrees | Brute - Optimal", 20),
      ],
    },

    {
      chapterId: "ch_str_02",
      chapterOrder: 2,
      chapterTitle: "Step 2 – Sorting Techniques",
      chapterContent: [
        lec("3Zv-s9UUrFM", "Spiral Traversal of a Matrix | Spiral Matrix", 20, true),
        lec("xvNwoz-ufXA", "Count Subarray sum Equals K | Brute - Better -Optimal", 20, true),
        lec("bR7mQgwQ_o8", "Pascal Triangle | Finding nCr in minimal time", 20),
        lec("vwZj1K0e9U8", "Majority Element II | Brute-Better-Optimal", 20),
        lec("DhFh8Kw7ymk", "3 Sum | Brute -  Better - Optimal with Codes", 20),
        lec("eD95WRfh81c", "4 Sum | Brute - Better - Optimal with Codes", 20),
        lec("eZr-6p0B7ME", "Number of Subarrays with xor K | Brute - Better - Optimal", 20),
      ],
    },

    {
      chapterId: "ch_str_03",
      chapterOrder: 3,
      chapterTitle: "Step 3 – Arrays [Easy → Medium → Hard]",
      chapterContent: [
        lec("IexN60k62jo", "Merge Overlapping Intervals | Brute, Optimal with Precise TC analysis", 20, true),
        lec("n7uwj04E0I4", "Merge Sorted Arrays Without Extra Space | 2 Optimal Solution", 20, true),
        lec("2D0D8HE6uak", "Find the Missing and Repeating Number | 4 Approaches 🔥", 20),
        lec("AseUmwVNaoY", "Count Inversions in an Array | Brute and Optimal", 20),
        lec("0e4bZaP3MDI", "Reverse Pairs | Hard Interview Question", 20),
        lec("hnswaLJvr6g", "Maximum Product Subarray - Best Intuitive Approach Discussed", 20),
        lec("MHf6awe89xw", "BS-1. Binary Search Introduction | Real Life Example | Iterative | Recursive | Overflow Cases", 20),
        lec("6zhGS79oQ4k", "BS-2. Implement Lower Bound and Upper Bound | Search Insert Position | Floor and Ceil", 20),
        lec("hjR1IYVx9lY", "BS-3. First and Last Occurrences in Array | Count occurrences in Array", 20),
        lec("5qGrJbHhqFs", "BS-4. Search Element in Rotated Sorted Array - I", 20),
        lec("w2G2W8l__pc", "BS-5. Search Element in Rotated Sorted Array II", 20),
        lec("nhEMDKMB44g", "BS-6. Minimum in Rotated Sorted Array", 20),
        lec("jtSiWTPLwd0", "BS-7. Find out how many times array has been rotated", 20),
        lec("AZOmHuHadxQ", "BS-8. Single Element in Sorted Array", 20),
        lec("cXxmbemS6XM", "BS-9. Find Peak Element", 20),
        lec("Bsv3FPUX_BA", "BS-10. Finding Sqrt of a number using Binary Search", 20),
        lec("rjEJeYCasHs", "BS-11. Find the Nth root of an Integer", 20),
        lec("qyfekrNni90", "BS-12. Koko Eating Bananas", 20),
        lec("TXAuxeYBTdg", "BS-13. Minimum days to make M bouquets | Binary Search", 20),
        lec("UvBKTVaG6U8", "BS-14. Find the Smallest Divisor Given a Threshold | Binary Search", 20),
        lec("MG-Ac4TAvTY", "BS-15. Capacity to Ship Packages within D Days", 20),
        lec("uZ0N_hZpyps", "BS-16. Kth Missing Positive Number | Maths + Binary Search", 20),
        lec("R_Mfw4ew-Vo", "BS-17. Aggressive Cows | Binary Search Hard", 20),
        lec("Z0hwjftStI4", "BS-18. Allocate Books or Book Allocation | Hard Binary Search", 20),
        lec("thUd_WJn6wk", "BS 19. Painter\\'s Partition and Split Array - Largest Sum", 20),
        lec("kMSBvlZ-_HA", "BS-20. Minimise Maximum Distance between Gas Stations | 3 Approaches | Heap | Binary Search", 20),
        lec("C2rRzz-JDk8", "BS 21: Median of two Sorted Arrays of Different Sizes | Brute and Better Approach", 20),
        lec("F9c7LpRZWVQ", "BS-21. Median of two Sorted Arrays of Different Sizes | Binary Search Approach With Intuition", 20),
        lec("D1oDwWCq50g", "Bs-22. K-th element of two sorted arrays | Binary Search Approach", 20),
        lec("SCz-1TtYxDI", "BS 23. Row with maximum number of 1s | Binary Search on 2D Arrays", 20),
        lec("JXU4Akft7yk", "BS-24. Search in a 2D Matrix - I | Binary Search of 2D", 20),
        lec("9ZbB397jU4k", "BS-25. Search in a 2D Matrix - II  |  Binary Search on 2D", 20),
        lec("nGGp5XBzC4g", "BS-26. Find Peak Element-II | Binary Search", 20),
        lec("Q9wXgdxJq48", "BS-27. Median in a Row Wise Sorted Matrix", 20),
        lec("_ANrF3FJm7I", "L1. Introduction to Trees | Types of Trees", 20),
        lec("ctCpP0RFDFc", "L2. Binary Tree Representation in C++", 20),
        lec("hyLyW7rP24I", "L3. Binary Tree Representation in Java", 20),
        lec("jmy0LaGET1I", "L4. Binary Tree Traversals in Binary Tree | BFS | DFS", 20),
        lec("RlUu72JrOCQ", "L5. Preorder Traversal of Binary Tree | C++ | Java | Code Explanation", 20),
        lec("Z_NEgBgbRVI", "L6. Inorder Traversal of Binary Tree | C++ | Java | Code Explanation", 20),
      ],
    },

    {
      chapterId: "ch_str_04",
      chapterOrder: 4,
      chapterTitle: "Step 4 – Binary Search [1D, 2D Arrays, Search Space]",
      chapterContent: [
        lec("COQOU6klsBg", "L7. Postorder Traversal of Binary Tree | C++ | Java | Code Explanation", 20, true),
        lec("EoAsWbO7sqg", "L8. Level Order Traversal of Binary Tree | BFS | C++ | Java", 20, true),
        lec("Bfqd8BsPVuw", "L9. Iterative Preorder Traversal in Binary Tree | C++ | Java | Stack", 20),
        lec("lxTGsVXjwvM", "L10. iterative Inorder Traversal in Binary Tree | C++ | Java | Stack", 20),
        lec("2YBhNLodD8Q", "L11. Iterative Postorder Traversal using 2 Stack | C++ | Java | Binary Tree", 20),
        lec("NzIGLLwZBS8", "L12. Iterative Postorder Traversal using 1 Stack | C++ | Java | Binary Trees", 20),
        lec("ySp2epYvgTE", "L13. Preorder Inorder Postorder Traversals in One Traversal | C++ | Java | Stack | Binary Trees", 20),
        lec("eD3tmO66aBA", "L14. Maximum Depth in Binary Tree | Height of Binary Tree | C++ | Java", 20),
        lec("Yt50Jfbd8Po", "L15. Check for Balanced Binary Tree | C++ | Java", 20),
        lec("Rezetez59Nk", "L16. Diameter of Binary Tree | C++ | Java", 20),
        lec("WszrfSwMz58", "L17. Maximum Path Sum in Binary Tree | C++ | Java", 20),
        lec("BhuvF_-PWS0", "L18. Check it two trees are Identical or Not | C++ | Java", 20),
        lec("3OXWEdlIGl4", "L19. Zig-Zag or Spiral Traversal in Binary Tree | C++ | Java", 20),
        lec("0ca1nvR0be4", "L20. Boundary Traversal in Binary Tree | C++ | Java", 20),
        lec("q_a6lpbKJdw", "L21. Vertical Order Traversal of Binary Tree | C++ | Java", 20),
        lec("Et9OCDNvJ78", "L22. Top View of Binary Tree | C++ | Java", 20),
        lec("0FtVY6I4pB8", "L23. Bottom View of Binary Tree | C++ | Java", 20),
        lec("KV4mRzTjlAk", "L24. Right/Left View of Binary Tree | C++ | Java", 20),
        lec("nKggNAiEpBE", "L25. Check for Symmetrical Binary Trees | C++ | Java", 20),
        lec("fmflMqVOC7k", "L26. Print Root to Node Path in Binary Tree | C++ | Java", 20),
        lec("_-QHfMDde90", "L27. Lowest Common Ancestor in Binary Tree | LCA | C++ | Java", 20),
        lec("ZbybYvcVLks", "L28. Maximum Width of Binary Tree | C++ | Java", 20),
        lec("fnmisPM6cVo", "L29. Children Sum Property in Binary Tree | O(N) Approach | C++ | Java", 20),
        lec("i9ORlEy6EsI", "L30. Print all the Nodes at a distance of K in Binary Tree | C++ | Java", 20),
        lec("2r5wLmQfD6g", "L31. Minimum time taken to BURN the Binary Tree from a Node | C++ | Java", 20),
        lec("u-yWemKGWO0", "L32. Count total Nodes in a COMPLETE Binary Tree | O(Log^2 N) Approach | C++ | Java", 20),
        lec("9GMECGQgWrQ", "L33. Requirements needed to construct a Unique Binary Tree | Theory", 20),
        lec("aZNaLrVebKQ", "L34. Construct a Binary Tree from Preorder and Inorder Traversal | C++ | Java", 20),
        lec("LgLRTaEMRVc", "L35. Construct the Binary Tree from Postorder and Inorder Traversal | C++ | Java", 20),
        lec("-YbXySKJsX8", "L36. Serialize and De-serialize Binary Tree | C++ | Java", 20),
        lec("80Zug6D1_r4", "L37. Morris Traversal | Preorder | Inorder | C++ | Java", 20),
        lec("sWf7k1x9XR4", "L38. Flatten a Binary Tree to Linked List | 3 Approaches | C++ | Java", 20),
      ],
    },

    {
      chapterId: "ch_str_05",
      chapterOrder: 5,
      chapterTitle: "Step 5 – Strings [Basic and Medium]",
      chapterContent: [
        lec("p7-9UvDQZ3w", "L39. Introduction to Binary Search Tree | BST", 20, true),
        lec("KcNt6v_56cc", "L40. Search in a Binary Search Tree | BST | C++ | Java", 20, true),
        lec("KSsk8AhdOZA", "L41. Ceil in a Binary Search Tree | BST | C++ | Java", 20),
        lec("xm_W1ub-K-w", "L42. Floor in a Binary Search Tree | BST | C++ | Java", 20),
        lec("FiFiNvM29ps", "L43. Insert a given Node in Binary Search Tree | BST | C++ | Java", 20),
        lec("kouxiP_H5WE", "L44. Delete a Node in Binary Search Tree | BST | C++ | Java", 20),
        lec("9TJYWh0adfk", "L45. K-th Smallest/Largest Element in BST", 20),
        lec("f-sj7I5oXEI", "L46. Check if a tree is a BST or BT | Validate a BST", 20),
        lec("cX_kPV_foZc", "L47. LCA in Binary Search Tree", 20),
        lec("UmJT3j26t1I", "L48. Construct a BST from a preorder traversal | 3 Methods", 20),
        lec("SXKAD2svfmI", "L49. Inorder Successor/Predecessor in BST | 3 Methods", 20),
        lec("D2jMcmxU4bs", "L50. Binary Search Tree Iterator | BST | O(H) Space", 20),
        lec("ssL3sHwPeb4", "L51. Two Sum In BST | Check if there exists a pair with Sum K", 20),
        lec("ZWGW7FminDM", "L52. Recover BST | Correct BST with two nodes swapped", 20),
        lec("X0oXMdtUDwo", "L53. Largest BST in Binary Tree", 20),
      ],
    },

    {
      chapterId: "ch_str_06",
      chapterOrder: 6,
      chapterTitle: "Step 6 – LinkedList [Single, Double, Medium, Hard]",
      chapterContent: [
        lec("M3_pLsDdeuU", "G-1. Introduction to Graph | Types | Different Conventions Used", 20, true),
        lec("3oI-34aPMWM", "G-2. Graph Representation in C++ | Two Ways to Represent", 20, true),
        lec("OsNklbh9gYI", "G-3. Graph Representation in Java | Two Ways to Represent", 20),
        lec("lea-Wl_uWXY", "G-4. What are Connected Components ?", 20),
        lec("-tgVpUgsQ5k", "G-5. Breadth-First Search (BFS) | C++ and Java | Traversal Technique in Graphs", 20),
        lec("Qzf1a--rhp8", "G-6. Depth-First Search (DFS) | C++ and Java | Traversal Technique in Graphs", 20),
        lec("ACzkVtewUYA", "G-7. Number of Provinces | C++ | Java | Connected Components", 20),
        lec("muncqlKJrH0", "G-8. Number of Islands | Number of Connected Components in Matrix | C++ | Java", 20),
        lec("C-2_uSRli8o", "G-9. Flood Fill Algorithm | C++ | Java", 20),
        lec("yf3oUhkvqA0", "G-10. Rotten Oranges | C++ | Java", 20),
        lec("BPlrALf1LDU", "G-11. Detect a Cycle in an Undirected Graph using BFS | C++ | Java", 20),
        lec("zQ3zgFypzX4", "G-12. Detect a Cycle in an Undirected Graph using DFS | C++ | Java", 20),
        lec("edXdVwkYHF8", "G-13. Distance of nearest cell having 1 | 0/1 Matrix | C++ | Java", 20),
        lec("BtdgAys4yMk", "G-14. Surrounded Regions | Replace O\\'s with X\\'s | C++ | Java", 20),
        lec("rxKcepXQgU4", "G-15. Number of Enclaves | Multi-source BFS | C++ | Java", 20),
        lec("7zmgQSJghpo", "G-16. Number of Distinct Islands | Constructive Thinking + DFS | C++ | Java", 20),
        lec("-vu34sct1g8", "G-17. Bipartite Graph | BFS | C++ | Java", 20),
        lec("KG5YFfR0j8A", "G-18. Bipartite Graph | DFS | C++ | Java", 20),
        lec("9twcmtQj4DU", "G-19. Detect cycle in a directed graph using DFS | Java | C++", 20),
        lec("uRbJ1OF9aYM", "G-20. Find Eventual Safe States - DFS", 20),
        lec("5lZ0iJMrUMk", "G-21. Topological Sort Algorithm | DFS", 20),
        lec("73sneFXuTEg", "G-22. Kahn\\'s Algorithm | Topological Sort Algorithm | BFS", 20),
        lec("iTBaI90lpDQ", "G-23. Detect a Cycle in Directed Graph | Topological Sort | Kahn\\'s Algorithm | BFS", 20),
        lec("WAOfKpxYHR8", "G-24. Course Schedule I and II | Pre-requisite Tasks | Topological Sort", 20),
        lec("2gtg3VsDGyc", "G-25. Find Eventual Safe States - BFS - Topological Sort", 20),
        lec("U3N_je7tWAs", "G-26. Alien Dictionary - Topological Sort", 20),
        lec("ZUFQfFaU-8U", "G-27. Shortest Path in Directed Acyclic Graph - Topological Sort", 20),
        lec("C4gxoTaI71U", "G-28. Shortest Path in Undirected Graph with Unit Weights", 20),
        lec("tRPda0rcf8E", "G-29. Word Ladder - I | Shortest Paths", 20),
        lec("DREutrv2XD0", "G-30. Word Ladder - 2 | Shortest Paths", 20),
        lec("AD4SFl7tu7I", "G-31. Word Ladder - 2 | Optimised Approach for Leetcode", 20),
      ],
    },

    {
      chapterId: "ch_str_07",
      chapterOrder: 7,
      chapterTitle: "Step 7 – Recursion [Pattern-wise]",
      chapterContent: [
        lec("V6H1qAeB-l4", "G-32. Dijkstra\\'s Algorithm - Using Priority Queue - C++ and Java - Part 1", 20, true),
        lec("PATgNiuTP20", "G-33. Dijkstra\\'s Algorithm - Using Set - Part 2", 20, true),
        lec("3dINsjyfooY", "G-34. Dijkstra\\'s Algorithm - Why PQ and not Q, Intuition, Time Complexity Derivation - Part 3", 20),
        lec("rp1SMw7HSO8", "G-35. Print Shortest Path - Dijkstra\\'s Algorithm", 20),
        lec("U5Mw4eyUmw4", "G-36. Shortest Distance in a Binary Maze", 20),
        lec("0ytpZyiZFhA", "G-37. Path With Minimum Effort", 20),
        lec("9XybHVqTHcQ", "G-38. Cheapest Flights Within K Stops", 20),
        lec("_BvEJ3VIDWw", "G-39. Minimum Multiplications to Reach End", 20),
        lec("_-0mx0SmYxA", "G-40. Number of Ways to Arrive at Destination", 20),
        lec("0vVofAhAYjc", "G-41. Bellman Ford Algorithm", 20),
        lec("YbY8cVwWAvw", "G-42. Floyd Warshall Algorithm", 20),
        lec("PwMVNSJ5SLI", "G-43. Find the City With the Smallest Number of Neighbours at a Threshold Distance", 20),
        lec("ZSPjZuZWCME", "G-44. Minimum Spanning Tree - Theory", 20),
        lec("mJcZjjKzeqk", "G-45. Prim\\'s Algorithm - Minimum Spanning Tree - C++ and Java", 20),
        lec("aBxjDBC4M1U", "G-46. Disjoint Set | Union by Rank | Union by Size | Path Compression", 20),
        lec("DMnDM_sxVig", "G-47. Kruskal\\'s Algorithm - Minimum Spanning Tree - C++ and Java", 20),
        lec("ZGr5nX-Gi6Y", "G-48. Number of Provinces - Disjoint Set", 20),
        lec("FYrl7iz9_ZU", "G-49. Number of Operations to Make Network Connected - DSU", 20),
        lec("FMwpt_aQOGw", "G-50. Accounts Merge - DSU", 20),
        lec("Rn6B-Q4SNyA", "G-51. Number of Islands - II - Online Queries - DSU", 20),
        lec("lgiz0Oup6gM", "G-52. Making a Large Island - DSU", 20),
        lec("OwMNX8SPavM", "G-53. Most Stones Removed with Same Row or Column - DSU", 20),
        lec("R6uoSjZ2imo", "G-54. Strongly Connected Components - Kosaraju\\'s Algorithm", 20),
        lec("qrAub5z8FeA", "G-55. Bridges in Graph - Using Tarjan\\'s Algorithm of time in and low time", 20),
        lec("j1QDfU21iZk", "G-56. Articulation Point in Graph", 20),
      ],
    },

    {
      chapterId: "ch_str_08",
      chapterOrder: 8,
      chapterTitle: "Step 8 – Bit Manipulation [Concepts & Problems]",
      chapterContent: [
        lec("tyB0ztf0DNY", "DP 1. Introduction to Dynamic Programming | Memoization | Tabulation | Space Optimization Techniques", 20, true),
        lec("mLfjzJsN8us", "DP 2. Climbing Stairs | Learn How to Write 1D Recurrence Relations", 20, true),
        lec("EgG3jsGoPvQ", "DP 3. Frog Jump | Dynamic Programming | Learn to write 1D DP", 20),
        lec("Kmh3rhyEtB8", "DP 4. Frog Jump with K Distance | Lecture 3 Follow Up Question", 20),
        lec("GrMBfJNk_NY", "DP 5. Maximum Sum of Non-Adjacent Elements | House Robber | 1-D | DP on Subsequences", 20),
        lec("3WaxQMELSkw", "DP 6. House Robber 2 | 1D DP | DP on Subsequences", 20),
        lec("AE39gJYuRog", "DP 7. Ninja\\'s Training | MUST WATCH for 2D CONCEPTS 🔥 | Vacation | Atcoder | 2D DP |", 20),
        lec("sdE0A2Oxofw", "DP 8. Grid Unique Paths | Learn Everything about DP on Grids | ALL TECHNIQUES 🔥", 20),
        lec("TmhpgXScLyY", "DP 9. Unique Paths 2 | DP on Grid with Maze Obstacles", 20),
        lec("_rgTlyky1uQ", "DP 10. Minimum Path Sum in Grid | Asked to me In Microsoft Internship Interview | DP on GRIDS", 20),
        lec("SrP-PiLSYC0", "DP 11. Triangle | Fixed Starting Point and Variable Ending Point | DP on GRIDS", 20),
        lec("N_aJ5qQbYA0", "DP 12. Minimum/Maximum Falling Path Sum | Variable Starting and Ending Points | DP on Grids", 20),
        lec("QGfn7JeXK54", "DP 13. Cherry Pickup II | 3D DP Made Easy | DP On Grids", 20),
        lec("fWX9xDmIzRI", "DP 14. Subset Sum Equals to Target | Identify DP on Subsequences and Ways to Solve them", 20),
        lec("7win3dcgo3k", "DP 15. Partition Equal Subset Sum | DP on Subsequences", 20),
        lec("GS_OqZb2CWc", "Dp 16. Partition A Set Into Two Subsets With Minimum Absolute Sum Difference | DP on Subsequences", 20),
        lec("ZHyb-A2Mte4", "DP 17. Counts Subsets with Sum K | Dp on Subsequences", 20),
        lec("zoilQD1kYSg", "DP 18. Count Partitions With Given Difference | Dp on Subsequences", 20),
      ],
    },

    {
      chapterId: "ch_str_09",
      chapterOrder: 9,
      chapterTitle: "Step 9 – Stacks & Queues",
      chapterContent: [
        lec("GqOmJHQZivw", "DP 19. 0/1 Knapsack | Recursion to Single Array Space Optimised Approach | DP on Subsequences", 20, true),
        lec("myPeWb3Y68A", "DP 20. Minimum Coins | DP on Subsequences | Infinite Supplies Pattern", 20, true),
        lec("b3GD8263-PQ", "DP 21. Target Sum | DP on Subsequences", 20),
        lec("HgyouUi11zk", "DP 22. Coin Change 2 | Infinite Supply Problems  | DP on Subsequences", 20),
        lec("OgvOZ6OrJoY", "DP 23. Unbounded Knapsack | 1-D Array Space Optimised Approach", 20),
        lec("mO8XpGoJwuo", "DP 24. Rod Cutting Problem | 1D Array Space Optimised Approach", 20),
        lec("NPZn9jBrX8U", "Dp 25. Longest Common Subsequence | Top Down | Bottom-Up | Space Optimised | DP on Strings", 20),
        lec("-zI4mrF2Pb4", "DP 26. Print Longest Common Subsequence | Dp on Strings", 20),
        lec("_wP9mWNPL5w", "DP 27. Longest Common Substring | DP on Strings 🔥", 20),
        lec("6i_T5kkfv4A", "DP 28. Longest Palindromic Subsequence", 20),
        lec("xPBLEj41rFU", "DP 29. Minimum Insertions to Make String Palindrome", 20),
        lec("yMnH0jrir0Q", "DP 30. Minimum Insertions/Deletions to Convert String A to String B", 20),
        lec("xElxAuBcvsU", "DP 31. Shortest Common Supersequence | DP on Strings", 20),
        lec("nVG7eTiD2bY", "DP 32. Distinct Subsequences | 1D Array Optimisation Technique 🔥", 20),
        lec("fJaKO8FbDdo", "DP 33. Edit Distance | Recursive to 1D Array Optimised Solution 🔥", 20),
        lec("ZmlQ3vgAOMo", "DP 34. Wildcard Matching | Recursive to 1D Array Optimisation 🔥", 20),
        lec("nGJmxkUJQGs", "DP 36. Buy and Sell Stock - II | Recursion to Space Optimisation", 20),
        lec("-uQGzhYj8BQ", "DP 37. Buy and Sell Stocks III | Recursion to Space Optimisation", 20),
        lec("IV1dHbk5CDc", "DP 38. Buy and Stock Sell IV | Recursion to Space Optimisation", 20),
        lec("IGIe46xw3YY", "DP 39. Buy and Sell Stocks With Cooldown | Recursion to Space Optimisation", 20),
        lec("k4eK-vEmnKg", "DP 40. Buy and Sell Stocks With Transaction Fee | Recursion to Space Optimisation", 20),
        lec("ekcwMsSIzVc", "DP 41. Longest Increasing Subsequence | Memoization", 20),
        lec("IFfYfonAFGc", "DP 42. Printing Longest Increasing Subsequence | Tabulation | Algorithm", 20),
        lec("on2hvxBXJH4", "DP 43. Longest Increasing Subsequence | Binary Search | Intuition", 20),
        lec("gDuZwBW9VvM", "DP 44. Largest Divisible Subset | Longest Increasing Subsequence", 20),
        lec("YY8iBaYcc4g", "DP 45. Longest String Chain | Longest Increasing Subsequence | LIS", 20),
        lec("y4vN0WNdrlg", "DP 46. Longest Bitonic Subsequence | LIS", 20),
        lec("cKVl1TFdNXg", "DP 47. Number of Longest Increasing Subsequences", 20),
        lec("vRVfmbCFW7Y", "DP 48. Matrix Chain Multiplication | MCM | Partition DP Starts 🔥", 20),
        lec("pDCXsbAw5Cg", "DP 49. Matrix Chain Multiplication | Bottom-Up | Tabulation", 20),
      ],
    },

    {
      chapterId: "ch_str_10",
      chapterOrder: 10,
      chapterTitle: "Step 10 – Sliding Window & Two Pointer Problems",
      chapterContent: [
        lec("xwomavsC86c", "DP 50. Minimum Cost to Cut the Stick", 20, true),
        lec("Yz4LlDSlkns", "DP 51. Burst Balloons | Partition DP | Interactive G-Meet Session Update", 20, true),
        lec("MM7fXopgyjw", "DP 52. Evaluate Boolean Expression to True | Partition DP", 20),
        lec("_H8V5hJUGd0", "DP 53. Palindrome Partitioning - II | Front Partition 🔥", 20),
        lec("PhWWJmaKfMc", "DP 54. Partition Array for Maximum Sum | Front Partition 🔥", 20),
        lec("tOylVCugy9k", "DP 55. Maximum Rectangle Area with all 1\\'s | DP on Rectangles", 20),
        lec("auS1fynpnjo", "DP 56. Count Square Submatrices with All Ones | DP on Rectangles 🔥", 20),
        lec("Nq7ok-OyEpg", "L1. Introduction to LinkedList | Traversal | Length | Search an Element", 20),
        lec("VaECK03Dz-g", "L2. Deletion and Insertion in LL | 8 Problems", 20),
        lec("0eKMU10uEDI", "L3. Introduction to Doubly LinkedList | Insertions and Deletions", 20),
        lec("u3WUW2qe6ww", "L4. Reverse a DLL | Multiple Approaches", 20),
        lec("XmRrGzR6udg", "L5. Add 2 numbers in LinkedList | Dummy Node Approach", 20),
      ],
    },

    {
      chapterId: "ch_str_11",
      chapterOrder: 11,
      chapterTitle: "Step 11 – Heaps [Learning, Medium, Hard]",
      chapterContent: [
        lec("qf6qp7GzD5Q", "L6. Odd Even Linked List | Multiple Approaches", 20, true),
        lec("gRII7LhdJWc", "L7. Sort a LinkedList of 0\\'s, 1\\'s and 2\\'s | Multiple Approaches", 20, true),
        lec("3kMKYQ2wNIU", "L8. Remove Nth Node from the end of the LinkedList | Multiple Approaches", 20),
        lec("D2vI2DNJGd8", "L9. Reverse a LinkedList | Iterative and Recursive", 20),
        lec("lRY_G-u_8jk", "L10. Check if a LinkedList is Palindrome or Not | Multiple Approaches", 20),
        lec("aXQWhbvT3w0", "L11. Add 1 to a number represented by LinkedList", 20),
        lec("0DYoPz2Tpt4", "L12. Find the intersection point of Y LinkedList", 20),
        lec("7LjQ57RqgEc", "L13. Find the middle element of the LinkedList | Multiple Approaches", 20),
        lec("wiOo4DC5GGA", "L14. Detect a loop or cycle in LinkedList | With proof and Intuition", 20),
        lec("I4g1qbkTPus", "L15. Find the length of the Loop in LinkedList", 20),
        lec("ePpV-_pfOeI", "L16. Delete the middle node of the LinkedList", 20),
        lec("2Kd0KKmmHFc", "L17. Find the starting point of the Loop/Cycle in LinkedList | Multiple Approaches", 20),
        lec("Mh0NH_SD92k", "L18. Delete all occurrences of a Key in DLL", 20),
        lec("YitR4dQsddE", "L19. Find all Pairs with given Sum in DLL", 20),
        lec("YJKVTnOJXSY", "L20. Remove duplicates from sorted DLL", 20),
        lec("lIar1skcQYI", "L21. Reverse Nodes in K Group Size of LinkedList", 20),
        lec("uT7YI7XbTY8", "L22. Rotate a LinkedList", 20),
      ],
    },

    {
      chapterId: "ch_str_12",
      chapterOrder: 12,
      chapterTitle: "Step 12 – Greedy Algorithms",
      chapterContent: [
        lec("jXu-H7XuClE", "L23. Merge two sorted Linked Lists", 20, true),
        lec("ykelywHJWLg", "L24. Flattening a LinkedList | Multiple Approaches with Dry Run", 20, true),
        lec("1zktEppsdig", "L25. Merge K Sorted Lists | Multiple Approaches", 20),
        lec("8ocB7a_c-Cc", "L26. Sort a Linked List | Merge Sort and Brute Force", 20),
        lec("q570bKdrnlw", "L27. Clone a LinkedList with Next and Random Pointers | Copy List with Random Pointers", 20),
        lec("mG3KLugbOdc", "L28. Design a Browser History | LinkedList Implementation", 20),
        lec("Ae_Ag_saG9s", "L2. Print all Divisors of a Number | Maths Playlist", 20),
        lec("MJcckSfoYdI", "L3. Check if a Number if Prime or not | Maths Playlist", 20),
        lec("LT7XhVdeRyg", "L4. Print all prime factors of a Number | Maths Playlist", 20),
        lec("hFWckDXE-K8", "L5. Power Exponentiation | Maths Playlist", 20),
        lec("g5Fuxn_AvSk", "L6. Sieve of Eratosthenes | Maths Playlist", 20),
        lec("os82DjD2-MA", "L7. Count Prime in a range L-R | Maths Playlist", 20),
        lec("glKWkmKFlMw", "L8. Smallest Prime Factor (SPF) | Prime Factorisation | Query Based Problem | Maths Playlist", 20),
        lec("9kdHxplyl5I", "L1. Introduction to Sliding Window and 2 Pointers | Templates | Patterns", 20),
        lec("pBWCOCS636U", "L2. Maximum Points You Can Obtain from Cards | 2 Pointers and Sliding Window Playlist", 20),
        lec("-zSxTJkcdAo", "L3. Longest Substring Without Repeating Characters | 2 Pointers and Sliding Window Playlist", 20),
      ],
    },

    {
      chapterId: "ch_str_13",
      chapterOrder: 13,
      chapterTitle: "Step 13 – Binary Trees [Traversals, Medium, Hard]",
      chapterContent: [
        lec("3E4JBHSLpYk", "L4. Max Consecutive Ones III | 2 Pointers and Sliding Window Playlist", 20, true),
        lec("e3bs0uA1NhQ", "L5. Fruit Into Baskets | 2 Pointers and Sliding Window Playlist", 20, true),
        lec("teM9ZsVRQyc", "L6. Longest Substring With At Most K Distinct Characters | 2 Pointers and Sliding Window Playlist", 20),
        lec("xtqN4qlgr8s", "L7. Number of Substrings Containing All Three Characters | 2 Pointers and Sliding Window Playlist", 20),
        lec("_eNhaDCr6P0", "L8. Longest Repeating Character Replacement | 2 Pointers and Sliding Window Playlist", 20),
        lec("XnMdNUkX6VM", "L9. Binary Subarrays With Sum | 2 Pointers and Sliding Window Playlist", 20),
        lec("j_QOv9OT9Og", "L10. Count number of Nice subarrays | 2 Pointers and Sliding Window Playlist", 20),
        lec("7wYGbV_LsX4", "L11. Subarray with k different integers | 2 Pointers and Sliding Window Playlist", 20),
        lec("WJaij9ffOIY", "L12. Minimum Window Substring | 2 Pointers and Sliding Window Playlist", 20),
        lec("DIX2p7vb9co", "L1. Assign Cookies | Greedy Algorithm Playlist", 20),
        lec("3-QbX1iDbXs", "L3. Shortest Job First (or SJF) CPU Scheduling", 20),
        lec("n_tmibEhO6Q", "L2. Lemonade Change | Greedy Algorithm Playlist", 20),
        lec("tZAa_jJ3SwQ", "L4. Jump Game - I | Greedy Algorithm Playlist", 20),
        lec("7SBVnw7GSTk", "L5. Jump Game - II | Greedy Algorithm Playlist", 20),
        lec("QbwltemZbRg", "L6. Job Sequencing Problem | Greedy Algorithm Playlist", 20),
        lec("mKfhTotEguk", "L7. N Meeting in One Room | Greedy Algorithms Playlist", 20),
        lec("HDHQ8lAWakY", "L8. Non Overlapping Intervals | Greedy Algorithms Playlist", 20),
        lec("xxRE-46OCC8", "L9. Insert Intervals | Greedy Algorithms Playlist", 20),
        lec("AsGzwR_FWok", "L10. Minimum number of platforms required in a railway station", 20),
        lec("cHT6sG_hUZI", "L11. Valid Parenthesis String | Multiple Approaches", 20),
        lec("1ibsQrnuEEg", "L13. Fractional Knapsack Algorithm", 20),
        lec("IIqVFvKE6RY", "L12. Candy | Slope Approach Intuition Based", 20),
        lec("tqQ5fTamIN4", "L1. Introduction to Stack and Queue | Implementation using Data Structures", 20),
        lec("xwjS0iZhw4I", "L2. Check for Balanced Parentheses | Stack and Queue", 20),
        lec("4pIc9UBHJtk", "L3. Prefix, Infix, and Postfix Conversion | Stack and Queue Playlist", 20),
        lec("NdDIaH91P0g", "L4. Implement Min Stack | Stack and Queue Playlist", 20),
        lec("e7XQLtOQM3I", "L5. Next Greater Element | Stack and Queue Playlist", 20),
        lec("7PrncD7v9YQ", "L6. Next Greater Element - II | Stack and Queue Playlist", 20),
        lec("zMdbdGJNlh4", "L7. Previous Smaller Element | Stack and Queue Playlist", 20),
        lec("1_5VuquLbXg", "L8. Trapping Rainwater | 2 Approaches | Stack and Queue Playlist", 20),
        lec("v0e8p9JCgRc", "L9. Sum of Subarray Minimum | Stack and Queue Playlist", 20),
        lec("gIrMptNPf5M", "L10. Sum of subarray ranges | Stack and Queue Playlist", 20),
        lec("_eYGqw_VDR4", "L11. Aestroid Collisions | Stack and Queue Playlist", 20),
        lec("Bzat9vgD0fs", "L12. Largest Rectangle in Histogram | Stack and Queue Playlist", 20),
        lec("ttVu6G7Ayik", "L13. Maximal Rectangle | Stack and Queue Playlist", 20),
        lec("jmbuRzYPGrg", "L14. Remove K Digits | Stack and Queue Playlist", 20),
        lec("eay-zoSRkVc", "L15. Stock Span Problem | Stack and Queue Playlist", 20),
        lec("NwBvene4Imo", "L16. Sliding Window Maximum | Stack and Queue Playlist", 20),
        lec("cEadsbTeze4", "L17. The Celebrity Problem | Stack and Queue Playlist", 20),
      ],
    },

    {
      chapterId: "ch_str_14",
      chapterOrder: 14,
      chapterTitle: "Step 14 – Binary Search Trees [Concepts & Problems]",
      chapterContent: [
        lec("z9bJUPxzFOw", "L18. Implement LRU Cache", 20, true),
        lec("mzqHlAW7jeE", "Implement LFU cache in C++/Java  | Leetcode(Hard)", 20, true),
        lec("M4IHWsk-EAM", "Private video", 20),
      ],
    },

    {
      chapterId: "ch_str_15",
      chapterOrder: 15,
      chapterTitle: "Step 15 – Graphs [BFS, DFS, Topo Sort, Shortest Path, DSU, MST]",
      chapterContent: [

      ],
    },

    {
      chapterId: "ch_str_16",
      chapterOrder: 16,
      chapterTitle: "Step 16 – Dynamic Programming [All Patterns — 56 Problems]",
      chapterContent: [

      ],
    },

    {
      chapterId: "ch_str_17",
      chapterOrder: 17,
      chapterTitle: "Step 17 – Tries [Implementation + Problems]",
      chapterContent: [

      ],
    },

    {
      chapterId: "ch_str_18",
      chapterOrder: 18,
      chapterTitle: "Step 18 – Advanced Strings [KMP, Z-algo, Manacher]",
      chapterContent: [

      ],
    },
  ],
};

const seed = async () => {
  try {
    const uri = process.env.MONGODB_URI;
    if (!uri) throw new Error("MONGODB_URI not set");
    console.log("🔗 Connecting to MongoDB...");
    await mongoose.connect(`${uri}/LMS`);
    console.log("✅ Connected\n");

    const del = await Course.deleteOne({ courseTitle: /Striver/i });
    if (del.deletedCount) console.log("🗑  Removed old Striver course");

    const inserted = await Course.create(striverA2Z);
    const total = inserted.courseContent.reduce((s,c) => s + c.chapterContent.length, 0);

    console.log(`\n🎉 Seeded: ${inserted.courseTitle}`);
    console.log(`   Steps: ${inserted.courseContent.length} | Videos: ${total}\n`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Error:", err.message);
    process.exit(1);
  }
};

seed();
